<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           targetNamespace="http://example.com/customer"
           xmlns:tns="http://example.com/customer">

    <!-- Definizione dell'elemento radice "item" -->
    <xs:element name="item" type="tns:CustomerType"/>

    <!-- Definizione del tipo complesso "CustomerType" -->
    <xs:complexType name="CustomerType">
        <xs:sequence>
            <xs:element name="id" type="xs:int" minOccurs="1" maxOccurs="1"/>
            <xs:element name="first_name" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="last_name" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="email" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="car_id" type="xs:int" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>